[build]
  command = "NEXT_SKIP_TYPECHECKING=1 NEXT_SKIP_LINTING=1 next build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_SKIP_TYPECHECKING = "1"
  NEXT_SKIP_LINTING = "1"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*; font-src 'self' data:; connect-src 'self' https://api.stripe.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://source.unsplash.com/*"]
