[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_SKIP_TYPECHECKING = "1"
  NEXT_SKIP_LINTING = "1"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["node_modules/@sparticuz/chromium/**"]

[images]
  remote_images = ["https://source.unsplash.com/*", "https://ae01.alicdn.com/*", "https://images.unsplash.com/*", "https://plus.unsplash.com/*", "https://source.unsplash.com/random/800x600/?construction", "https://assets.usesi.com/*", "https://www.clarkdietrich.com/*", "https://thumbs.dreamstime.com/*", "https://c8.alamy.com/*", "https://st2.depositphotos.com/*"]
